### ISSUE TITLE
Set memory and CPU limits to new deployments

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/manager#20]
As of [`deis-api@0.0.14`](https://github.com/aledbf/deis-api/tree/v0.0.14), setting new apps' mem and cpu limits is supported.

We should out of the box set limits to 512MB of RAM and something small regarding CPU shares. CPU shares is a number between `100` and `1024` per cluster node.

We should:
1. set memory limits (we know 512 is good enough for a running `nodejs` app)
2. test different CPU share values on a running app (start from `100` and see if it looks good)
3. set resulting CPU share limit as part of a `deployment` creation in `manager`

**Comment by mjlescano** [comment]
Closed by https://github.com/DemocracyOS/manager/commit/197b5b390451b410a4b29e75b03c8431cd525854
