### ISSUE TITLE
Allow updating existing apps to newer docker images

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/manager#30]
I need to do some research. It may be a `Deis` thing, or it may be able to happen from external calls.

**Comment by gvilarino** [comment]
So, from what I've gathered so far, what we would do from the CLI for this would be:
1. Pull new base `docker` image into `deis`' internall registry
2. `deis pull internalRegistryIP:5000/newImage --app existingAppIWantToUpdate`
3. ???
4. Profit!!

I guess that for doing this with `deis-api` we could use the same approach we're currently using for deploying new apps only we don't create them, just `deis pull` on them with the new version. Please correct me if I'm wrong @mjlescano 

So, I guess a sensible approach for `manager` would be to have some sort of mechanism for knowing a new release is available and then having a rolling update one instance at a time. Each particular update should look like:
1. Set `deployment` status to `updating`
2. perform pull
3. wait for appropriate response from the newly deployed app
   1. If a timeout is reached (1 minute?) or there's an error, rollback to previous version (there is a `deis` command for that.

Thoughts?

**Comment by mjlescano** [comment]
Looks good!

But, we're not taking in mind the `env vars`. For the time being we can handle them by hand, but on the long term it's very likely that different `app` versions will need different `env vars`, and Manager should be able to handle them. Some sort of "sets" of `env vars` for each `app` version.
