### ISSUE TITLE
Add API support for knowing a user's deployment status

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/manager#5]
This is needed for https://github.com/DemocracyOS/hub/issues/58

API call param should be the user's ID, but can also be the deployment name so it's more generic.

Possible statuses are:
- `undefined`: deployment doesn't exist
- `ready`: created, up and running
- `creating`: it's been created by `manager`
- `destroyed`: it's been destroyed by manager

**Comment by mjlescano** [comment]
Closed by https://github.com/DemocracyOS/manager/pull/14
