### ISSUE TITLE
Delete feeds

### ISSUE THREAD

**Issue by sachalifs** [DemocracyOS/manager#7]
When deleting a `deployment`, their `feeds` should be deleted as well

**Comment by mjlescano** [comment]
This is already done in: https://github.com/DemocracyOS/manager/commit/9cb64042dc65f3730ba62d962f697c7897ecbe83 (and deployed to heroku).

But, we also have to merge this pulls:
- https://github.com/DemocracyOS/hub/pull/65
- https://github.com/DemocracyOS/notifier/pull/31
- https://github.com/DemocracyOS/app/pull/702
